# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  virtual_joint/trans_x:
    has_velocity_limits: true
    max_velocity: 0.02
    has_acceleration_limits: true
    max_acceleration: 0.04
  virtual_joint/trans_y:
      has_velocity_limits: true
      max_velocity: 0.02
      has_acceleration_limits: true
      max_acceleration: 0.04
  virtual_joint/trans_z:
      has_velocity_limits: true
      max_velocity: 0.02
      has_acceleration_limits: true
      max_acceleration: 0.04
  virtual_joint/rot_x:
      has_velocity_limits: true
      max_velocity: 0.02
      has_acceleration_limits: true
      max_acceleration: 0.04
  virtual_joint/rot_y:
      has_velocity_limits: true
      max_velocity: 0.02
      has_acceleration_limits: true
      max_acceleration: 0.04
  virtual_joint/rot_z:
      has_velocity_limits: true
      max_velocity: 0.02
      has_acceleration_limits: true
      max_acceleration: 0.04
  virtual_joint/rot_w:
      has_velocity_limits: true
      max_velocity: 0.02
      has_acceleration_limits: true
      max_acceleration: 0.04
